### PR TITLE
142 component service route

### PR DESCRIPTION
**Pull request by chilicoder**
addresses #142 
duplicates #209

### CODE REVIEW

**Comment by chilicoder** [comment]
Is it possible to get smbd’s fork and proceed with it?

**Comment by chilicoder** [comment]
If it is possible, Ill take yours and proceed

**Comment by allthesignals** [comment]
@chilicoder here's the branch - thanks! https://github.com/allthesignals/ember-decorators/tree/142-es6-classes-blueprint-components

**Comment by pzuraq** [comment]
Looks like this is just for `Component`, do you want to add `Service` and `Route` to this one as well?

**Comment by chilicoder** [comment]
@pzuraq here still some work have to be done.
now I rebase it against @allthesignals branch to pull in his commits. then I will add tests for components for unification, addons and both. and then clean the stuff. I will ping you when it will be ready

**Comment by chilicoder** [comment]
@pzuraq Ok. I think I'm done. Please, review it again. Since a lot of rebasing, moving to packages... and travis somehow doesn't run

**Comment by pzuraq** [comment]
Thanks for getting this over the line!

**Pull request merged**
