### PR TITLE
chore: Migrate from moduleFor* syntax

### PR DESCRIPTION
**Pull request by josemarluedke**
Used https://github.com/ember-codemods/ember-qunit-codemod

Should help with test issues in #451.

cc/ @rwjblue

### CODE REVIEW

**Comment by josemarluedke** [comment]
Test failure seems to be unrelated to my change:




```
-> $ yarn dtslint


Error: Errors in typescript@next for external dependencies:
../../../node_modules/@types/node/index.d.ts(187,11): error TS2300: Duplicate identifier 'IteratorResult'.
../../../node_modules/dtslint/typescript-installs/next/node_modules/typescript/lib/lib.es2015.iterable.d.ts(41,6): error TS2300: Duplicate identifier 'IteratorResult'.

    at /Users/josemarluedke/code/oss/ember-decorators/node_modules/dtslint/bin/index.js:163:19
    at Generator.next (<anonymous>)
    at fulfilled (/Users/josemarluedke/code/oss/ember-decorators/node_modules/dtslint/bin/index.js:5:58)
error Command failed with exit code 1.
```

**Comment by buschtoens** [comment]
This is the same issue as https://github.com/ember-decorators/ember-decorators/pull/451#issuecomment-508412735. You can fix this via d2f8b57e01ec6f1f32f3235a4d7f0b01a62ce248.

**Comment by josemarluedke** [comment]
Cherry-picked that commit here. Let's see if tests pass. :D 

Thanks @buschtoens for pointing that out.

**Comment by rwjblue** [comment]
```
  - stack: /home/travis/build/ember-decorators/ember-decorators/node_modules/@ember-data/-build-infra/node_modules/broccoli-rollup/dist/index.js:31
702    async build() {
703          ^^^^^
704
705SyntaxError: Unexpected identifier
```

Looks like we are getting screwed now by a node 6 incompatibility :weary:

**Comment by rwjblue** [comment]
We will need to lock ember-data to an earlier version (seems like [3.7 is what our yarn.lock](https://github.com/ember-decorators/ember-decorators/blob/9f6af93075f1c2c216759e4e763ab487d382958b/yarn.lock#L6630))

https://github.com/ember-decorators/ember-decorators/blob/9f6af93075f1c2c216759e4e763ab487d382958b/packages/-ember-decorators/package.json#L59

**Comment by josemarluedke** [comment]
@rwjblue Pushed a change to ping Ember Data version to 3.7.0. Thanks for pointing that out.

**Comment by josemarluedke** [comment]
@rwjblue Locking Ember data did not work out. I just cherry-picked all commits from @buschtoens from his branch. These commits do remove support for node 6 and 7.

Beta and Canary tests are now failing, changes from #451 will fix that.

**Comment by rwjblue** [comment]
@josemarluedke - Looks like we still need to update the engines in `ackages/-ember-decorators/package.json`.

**Comment by josemarluedke** [comment]
@rwjblue I believe this is ready now. Production tests are erroring out, but not related to these changes.

**Pull request merged**
