### PR TITLE
deleted private true repo

### PR DESCRIPTION
**Pull request by chilicoder**

### CODE REVIEW

**Comment by chilicoder** [comment]
looks like travis doesn't run otherwise

**Comment by pzuraq** [comment]
Ah that makes sense, probably why orbit.js doesn’t use Travis

**Comment by pzuraq** [comment]
Looks like Travis is running on #220 despite this, so maybe something else happened with your other PR that's causing it not to run. Can you try squashing the commits and seeing if that helps?

**Comment by chilicoder** [comment]
I just reopened it, travis goes

**Pull request closed without merging**
